name: Production project update
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    name: Build Docker image and push to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:production
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy housou service
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
      - name: Connect to remote server and rebuild project
        uses: appleboy/ssh-action@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          port: ${{ secrets.PRODUCTION_PORT }}
          envs: GITHUB_REPOSITORY
          script: |
            set -e
            cd ${HOME}/${GITHUB_REPOSITORY}
            docker compose pull
            docker compose up -d
